//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crProject.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("" +
            "")]
        public string librairieConnectionString {
            get {
               byte[] cle = System.Convert.FromBase64String("12UCgcnHy8LHoN/VodosrUVgv+r+kQ5e");
                byte[] iv = System.Convert.FromBase64String("AsJNO9N/4dM=");

                string cs = this["librairieConnectionString"].ToString();
                byte[] cryptedTextAsByte = System.Convert.FromBase64String(cs);

                System.Security.Cryptography.TripleDESCryptoServiceProvider TDES = new System.Security.Cryptography.TripleDESCryptoServiceProvider();

                // Cet objet est utilisé pour déchiffrer les données.
                // Il reçoit les données chiffrées sous la forme d'un tableau de bytes.
                // Les données déchiffrées sont également retournées sous la forme d'un tableau de bytes
                var decryptor = TDES.CreateDecryptor(cle, iv);

                byte[] decryptedTextAsByte = decryptor.TransformFinalBlock(cryptedTextAsByte, 0, cryptedTextAsByte.Length);

                return System.Text.Encoding.Default.GetString(decryptedTextAsByte);



            }
        }
    }
}
